### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ahmetbugraozcan** [Paradoxu/Caller#1]
Hi. I want to use your plugin but callerCallbackHandler in your example doesnt run. There isnt any error also there isnt any action. App asking me for permissions and i am giving permissions. After then there isnt any action in console if i get incoming call. Here is code 
```
import 'package:caller/caller.dart';
import 'package:flutter/material.dart';

/// Defines a callback that will handle all background incoming events
///
/// The duration will only have a value if the current event is `CallerEvent.callEnded`
Future<void> callerCallbackHandler(
    CallerEvent event,
    String number,
    int? duration,
    ) async {
  print("New event received from native $event");
  switch (event) {
    case CallerEvent.callEnded:
      print('Ended a call with number $number and duration $duration');
      break;
    case CallerEvent.onMissedCall:
      print('Missed a call from number $number');
      break;
    case CallerEvent.onIncomingCallAnswered:
      print('Accepted call from number $number');
      break;
    case CallerEvent.onIncomingCallReceived:
      print('Phone is ringing with number $number');
      break;
  }
}

Future<void> initialize() async {
  /// Check if the user has granted permissions
  final permission = await Caller.checkPermission();

  /// If not, then request user permission to access the Call State
  if (!permission)
    Caller.requestPermissions();
  else
    Caller.initialize(callerCallbackHandler);
}

void main() {
  initialize();

   runApp(MyApp());
}


//


class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

Note: If i make main async and run like this:
```
void main() async{
  await initialize();

   runApp(MyApp());
}
```
Caller.initialize method runs but it throws this error:
```
E/flutter ( 3987): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 3987): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
E/flutter ( 3987): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:146:36)
E/flutter ( 3987): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 3987): #3      Caller.requestPermissions (package:caller/caller.dart:65:20)
E/flutter ( 3987): #4      initialize (package:connectycubeexample/main.dart:35:12)
E/flutter ( 3987): <asynchronous suspension>
E/flutter ( 3987): #5      main (package:connectycubeexample/main.dart:43:3)
E/flutter ( 3987): <asynchronous suspension>
```

**Comment by Paradoxu** [comment]
Hi @ahmetbugraozcan  this issue should now be fixed with new published version `0.0.4`, you shall update your `AndroidManifest.xml` as said here: [Android](https://github.com/Paradoxu/Caller#android), please let me know if you are still facing any problems.
